#!/bin/bash

# Generated by Claude Sonnet 4.5 for the following request:
#
# Can you please draft a Bash script that would walk through files staring with a given pattern, and check that they all have the same lines (same order, same contents) if considering only the lines that start by a dot?
#
# Reviewed and slighly modified.

set -e

PATTERN="/tmp/schedules-*"
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

# Find all files matching the pattern
FILES=($(ls $PATTERN 2>/dev/null))

if [ ${#FILES[@]} -eq 0 ]; then
    echo "Error: No files found matching pattern '$PATTERN'"
    exit 1
fi

echo "Found ${#FILES[@]} file(s) matching pattern '$PATTERN'"
echo ""

# Extract dot-lines from each file
for i in "${!FILES[@]}"; do
    FILE="${FILES[$i]}"
    if [ ! -f "$FILE" ]; then
        echo "Warning: '$FILE' is not a regular file, skipping"
        continue
    fi
    
    grep "^\." "$FILE" > "$TEMP_DIR/dotlines_$i.txt" 2>/dev/null || touch "$TEMP_DIR/dotlines_$i.txt"
    echo "Processing: $FILE"
done

echo ""

# Compare all extracted dot-lines files
REFERENCE="$TEMP_DIR/dotlines_0.txt"
ALL_MATCH=true

for i in $(seq 1 $((${#FILES[@]} - 1))); do
    CURRENT="$TEMP_DIR/dotlines_$i.txt"
    
    if ! diff -q "$REFERENCE" "$CURRENT" > /dev/null 2>&1; then
        ALL_MATCH=false
        echo "'${FILES[0]}' and '${FILES[$i]}' have differences."
    fi
done

if [ "$ALL_MATCH" = true ]; then
    echo "All files have identical dot-lines (same content and order)."
    exit 0
else
    echo "Files have inconsistent dot-lines."
    exit 1
fi